export const generalCategories = [
    'Old',
    'Young',
    'Mature',
    'Gay',
    'Classic',
    'Amateur',
    'Interracial',
    'Ebony',
    'Casting',
    'Teen',
    'MILF',
    'Vintage',
    'Big Dick',
    'Creampie',
    'Handjob',
    'Cunnilingus',
    'Bondage',
    'Fetish',
    'Masturbation',
    'Toys',
    'Lesbian',
    'Asian',
    'Solo Male',
    'Feet',
    'Cartoon',
    'Smoking',
    'Anal',
    'Female Friendly',
    'Babysitter',
    'Outdoor',
    'BBW',
    'Orgy',
    'Fisting',
    'Massage',
    'Gangbang',
    'Shemale',
    'Rough Sex',
    'Uniforms',
    'Bisexual',
    'Hardcore',
    'Striptease',
    'Bukkake',
    'Squirt',
    'Double Penetration',
    'Blowjob',
    'Babe',
    'Cumshots',
    'Threesome',
    'Big Tits',
    'Brunette',
    'Ass',
    'POV',
    'Small Tits',
    'College',
    'Blonde',
    'Hentai',
    'Red Head',
];
